FROM scratch

ARG IMAGE_VERSION

LABEL org.opencontainers.image.source="https://github.com/openads-project/point_cloud_object_detection" \
      org.opencontainers.image.description="Triton model repository for the point cloud object detection demo" \
      org.opencontainers.image.version="${IMAGE_VERSION}"

COPY point-cloud-object-detection/ /models/point-cloud-object-detection/
