include:
  - remote: https://raw.githubusercontent.com/ika-rwth-aachen/docker-ros/fix/slim/.gitlab-ci/docker-ros.yml

variables:
  DOCKER_ROS_GIT_REF: fix/slim
  BASE_IMAGE: rwthika/ros2-triton:jazzy
  PLATFORM: amd64,arm64
  RMW_IMPLEMENTATION: rmw_zenoh_cpp
  ENABLE_RECURSIVE_VCS_IMPORT: 'false'
  COMMAND: ros2 launch point_cloud_object_detection point_cloud_object_detection.launch.py
  ENABLE_INDUSTRIAL_CI: 'true'
  ENABLE_RECURSIVE_VCS_IMPORT: 'false'
  TARGET: dev,run
  TARGET_CMAKE_ARGS : '-DCMAKE_EXPORT_COMPILE_COMMANDS=1'
