<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>point_cloud_object_detection</name>
  <version>2.1.0</version>
  <description>Detects objects in point clouds</description>
  
  <maintainer email="bastian.lampe@rwth-aachen.de">Bastian Lampe</maintainer>

  <license>Apache-2.0</license>

  <author email="bastian.lampe@rwth-aachen.de">Bastian Lampe</author>
  <author email="fabian.thomsen@rwth-aachen.de">Fabian Thomsen</author>
  <author email="christian.geller@rwth-aachen.de">Christian Geller</author>
  <author email="lennart.reiher@rwth-aachen.de">Lennart Reiher</author>
  <author email="lukas.zanger@rwth-aachen.de">Lukas Zanger</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>pcl_conversions</depend>
  <depend>pcl_ros</depend>
  <depend>perception_msgs</depend>
  <depend>perception_msgs_utils</depend>
  <depend>ament_index_cpp</depend>
  <depend>point_cloud_transport</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>std_msgs</depend>
  <depend>triton_cpp</depend>
  <depend>tf2</depend>
  <depend>tf2_perception_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_sensor_msgs</depend>
  <depend>yaml-cpp</depend>
  
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_cmake_clang_format</test_depend>
  <test_depend>ament_cmake_clang_tidy</test_depend>
  <test_depend>ament_cmake_flake8</test_depend>

  <exec_depend>tracetools_launch</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
